### PR TITLE
Add support for vaimo/composer-patches

### PR DESCRIPTION
**Pull request by peterjaap**
This depends on this MR being merged in the vaimo repo; https://github.com/vaimo/composer-patches/pull/108

Output (see last column);

image

### CODE REVIEW

**Comment by danslo** [comment]
Thanks again @peterjaap . I refactored it a little bit into separate private methods.

Maybe at some point we can also support cweagan's patches, I believe it's also quite popular.

**Comment by danslo** [comment]
I've merged it here already, despite PR not being merged upstream... As it currently doesn't break anything :)

**Comment by peterjaap** [comment]
Doesn't break anything, but it will say "No" in the "Patch applied" column even though there might be patches installed. Let's hope Vaimo merges it soon :)

**Comment by peterjaap** [comment]
@danslo fix for the above; https://github.com/sansecio/composer-integrity-plugin/pull/7

**Pull request merged**
